<?php
    
define('GPAY_MERCHANT_ID', 'BCR2DN4TQPP6372M');
define('GPAY_MERCHANT_NAME', 'WJCW');
define('GPAY_ENV', 'TEST'); // TEST, PRODUCTION

define('PAYPAL_CLIENT_ID', 'AZlZvhlOraxBv3vQOTRBfGyxmvQRQMoPhM3JJhCaSf2B5yDePBDGhRCpSBGVc4i7AkWlMQB5kP5OVAV5');
define('PAYPAL_SECRET', 'EIE4krAkkFdcy3M0xv4waC3HrlXPmSyhW9dgYXRudEST5akvKMag5XTOIExM6LoFCxI-9BWvzUdLFTKh');

// define('PAYPAL_CLIENT_ID', 'AYMgAWRF1MvxpI-4vaaOwnR_S77BifjtNKBTxezsSPYqeXEEXp5Ys43lH8Mf7bfpQ2xrIRD5uNFYNeGt');
// define('PAYPAL_SECRET', 'EDc7Ox_Yq4f5LpF4BuNO-UEnENkygLL83Bbwn7LC60EUnWQAbmaz8zIySZFt6QmM9Ck-N7ONuMG1OUgx');
?>