<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="../assets/links/owl.carousel.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="../css/site.css">
    <link rel = "icon" href =  "../assets/images/cropped-logo.png" type = "image/x-icon"> 
    <title>Terms &amp; Conditions</title>

</head>

<body>
    <?php
    include"../google_translator.php";
    include("../header_footer/headers.php") ?>
       
        <section id="MainContent" class="bg-white py-5">
            <div class="container">
                <div class="row ">
                    <div class="col-auto col-md-10 ">
                        <nav aria-label="breadcrumb " class="first d-md-flex">
                            <ol class="breadcrumb indigo lighten-6 first-1 shadow-lg mb-5 ">
                                <li class="breadcrumb-item font-weight-bold"><a class="black-text text-uppercase " href="../index.php"><span>home</span></a><img class="ml-md-3" src="https://img.icons8.com/offices/30/000000/double-right.png" width="20" height="20"> </li>
                                <li class="breadcrumb-item font-weight-bold mr-0 pr-0"><a class="black-text active-1" href=""><span>TERMS AND CONDITIONS</span></a> </li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <h1>Terms &#038; Conditions</h1>
                <div class="clearfix">
                    <p>WJCW Crowdfunding Ltd., (hereafter WJCW CF) provides its services (described below) to you through the WJCW CF website and related services subject to the following Terms of Service</p>
                    <p>We reserve the sole right to change and/or revise parts of these Terms of Service which we will update via the associated WJCW CF website including the date of revision. We will also aim to notify you, either through the WJCW CF platform/portal/member interface, in an email, or through other reasonable means, and unless otherwise stated, WJCW CF may communicate with you officially by any reasonable means stated above or which are not yet stated as part of this Terms of Service but which WJCW CF may later use. Any changes to the Terms of Service or services provided by WJCW CF will come into effect by the date as stated on any communication indicating a revision to the Terms of Service unless (i) changes addressing new functions of WJCW CF services or changes ARE made for legal reasons and will therefore come into effect immediately. Your continued use of the services by WJCW CF after the date of any such change becomes effective will be considered your acceptance of the new Terms of Service. If you do not wish to accept any new Terms of Service, you can stop your use of the WJCW CF platform and all associated services.</p>
                    <p>Furthermore, you will be subject to any additional terms applicable when using certain services in addition to services provided by WJCW CF. This includes guarantees and terms and conditions as stipulated in the official WJCW Membership Form. All such terms are hereby incorporated by reference into these Terms of Service.</p>
                    <h2>Access and Use of the Services</h2>
                    <p><strong>Services Description:</strong> The services of WJCW CF are offered as a platform on which individuals can take part in crowdfunding. Individuals are “users” of the WJCW CF platform and may be deemed a “campaign organiser” and/or “donor” (each defined further below). Among other features, the services are designed to allow a user (a “campaign organiser”) to post a fundraising “campaign” to the WJCW CF Platform for the purpose of accepting monetary “donations” and/or “gifts” from other registered users wishing to contribute funds to the campaign. The term “campaign organiser” will also include in that definition any individual(s) designated as a beneficiary of a “campaign”. There are no fees to set up a campaign, but there is an annual platform fee, more details of this fee and further details can be found in the “Fees” section.</p>
                    <p><strong>Charitable Giving:</strong> Campaigns are not charities to which you can make taxdeductible charitable contributions. However, WJCW CF permits donors to contribute directly to certain charitable organisations (“charities”) through the Platform, in addition to the services described above.</p>
                    <p>WJCW CF is an administrative platform only from which users of said platform may use the website or associated platforms (such as mobile application, etc) to view the current status of individual accounts and manage online information individually.</p>
                    <p>WJCW CF is not a financial organisation or broker, creditor or charity. The services provided by WJCW CF are administrative only. WJCW CF facilitates the gifts/donation transactions between a campaign organisers and donors but is not a party to any agreement between a campaign organiser and a donor, or between any user and a charity.</p>
                    <p>WJCW CF is not liable for the conduct of, or any information provided by, a campaign organiser or a charity or donor and does not claim responsibility for the individual actions of others.</p>
                    <p>WJCW CF makes no guarantee, explicit or implied, that any information provided through the Services by a user is accurate. We expressly disclaim any liability or responsibility for the success of any campaign, or the outcome of any fundraising purpose. You, as a donor, must make the final determination as to the value and appropriateness of contributing to any campaign, campaign organiser, or charity.</p>
                    <p>We assume no responsibility to verify whether the gifts/donations are used in accordance with any applicable laws; such responsibility rests solely with the campaign organiser or charity, as applicable.</p>
                    <p>We take possible fraudulent activity and the misuse of funds raised very seriously. If you have reason to believe that a user of services provided by WJCW CF is not raising or using the funds for their stated purpose, please raise with WJCW Head Office or alert the WJCW CF team of any issues using contact details provided on the WJCW CF website.</p>
                    <h2>Membership Agreement:</h2>
                    <p>As a member and shareholder of WJCW, I confirm that I fulfill the two main requirements for members and shareholders of WJCW, namely that I am an adherent and follower of the Shia Ithna Ashari Fiqh-e-Jafari Madhab (school of thought) and that I am at least 18 years of age.</p>
                    <p><strong>Registration:</strong> If you choose to register for WJCW CF, or make use of any associated service, you agree to provide and maintain true, accurate, current and complete information about yourself as prompted by the registration and/or membership form.</p>
                    <p>If you are under 18 years of age, you are not authorised to use the services of either WJCW or WJCW CF, with or without registering.</p>
                    <p>Certain aspects of our Services may also require you to register with (and agree to the terms of) third-party service providers (e.g., payment processors or charitable gifts/donation processors) in order to utilise such services. While we may help facilitate such registration in some cases, we are not a party to any such relationships and disclaim any responsibility or liability for the performance by such third parties. We may exchange information with such third-party services in order to facilitate the provision of services (and related third party services). Personal Data will only be shared according to the Privacy Policy which will be available on the WJCW CF website.</p>
                    <p>Once you register as a member, please note that you must follow the rules set by WJCW CF. If you do not adhere to the rules, you risk having your account with WJCW CF terminated.</p>
                    <p>By becoming a member of WJCW CF, you agree to the following rules to continue to qualify as a member of WJCW:</p>
                    <ul>
                        <li>I agree to adhere to the regulations of WJCW. As a member of WJCW, I understand that it is my responsibility to adhere to the rules as a condition of my continued membership.</li>
                        <li>I agree to adhere to processes and rules of any gift scheme or WJCW crowdfunding or any other welfare campaign.</li>
                        <li>I declare that I am not and will not be involved in any illicit financial activities such as money laundering in my involvement within WJCW.</li>
                        <li>I declare that I will work with WJCW faithfully for the welfare of the community.</li>
                        <li>At any stage, I will not work against the stated objectives or work of WJCW.</li>
                    </ul>
                    <p>WJCW CF is a platform for members to support one another as one community in a number of different ways. The WJCW CF Objectives are outlined below:</p>
                    <ul>
                        <li>To promote harmony and unity between all followers of the Shia Fiqh-e-Jafaria.</li>
                        <li>To assist members in achieving a level of financial freedom through a variety of services and support.</li>
                        <li>To encourage entrepreneurialism amongst members and shareholders and supporting help for others using the WJCW CF platform</li>
                    </ul>
                    <p><strong>Taxes:</strong> the responsibility for taxes lie with the individual member who is responsible to ascertain if any taxes apply to the gift/donations one may receive through the use of the services provided by WJCW CF. It is solely your responsibility to assess, collect, report or remit the correct tax, if any, to the appropriate tax authority. Ordinarily, there is no tax payable on gifts/donations, but WJCW CF does not provide any tax advice. We strongly advise you to consult your tax advisor and/or accountant.</p>
                    <p><strong>Member Account, Password, and Security:</strong> You are responsible for maintaining the confidentiality of your password and account and are fully responsible for any and all activities that occur under your password or account. WJCW CF will not be liable for any loss or damage resulting from failure to be precautionary.</p>
                    <p><strong>Modifications to Services:</strong> WJCW CF reserves the right to modify, suspend or discontinue, temporarily or permanently, the services (or any part thereof). We will endeavor to give you notice of any such modification, suspension or discontinuance through the means states earlier in these Terms of Services. You agree that, to the extent permitted by law, WJCW CF will not be liable to you for any modification, suspension or discontinuance of the services in accordance with these Terms and Conditions.</p>
                    <p>You agree that WJCW CF has no responsibility or liability for the deletion or failure to store any data or other content maintained or uploaded by the services. You acknowledge that WJCW CF reserves the right to terminate accounts or campaigns that are inactive for an extended period of time, provided that WJCW CF will use its reasonable efforts to provide a user with reasonable notice before terminating an inactive account having a positive balance of gifts/donations. WJCW CF will endeavor to give you notice of any such change where required by applicable law.</p>
                    <h2>Conditions of Use</h2>
                    <p><strong>User Conduct:</strong> You are solely responsible for all Campaign descriptions, comments, videos, images, information, data, text, software, music, sound, photographs, graphics, messages or other materials (“content”) that you upload, post, publish or display (hereinafter, “upload”) or transmit or otherwise use via the Services. The following are examples of the kind of content and/or use that is illegal or prohibited by WJCW CF. However, this list is not exhaustive and WJCW CF reserves the right to investigate anyone by engaging public and private organisations, including, but not limited to collection agents, private investigators, and local, state, federal and applicable international agencies, and take appropriate action against anyone who, in WJCW CF’s discretion, violates any of the terms or spirit of these Terms of Service (or the principles described in our preamble hereto), including, without limitation, removing the offending content, suspending or terminating the account of such violators, stopping payments to any such Campaign, freezing or placing a hold on gifted/donated funds when WJCW CF reasonably believes it to be required by applicable law, and reporting you to law enforcement authorities or otherwise taking appropriate legal action. Without limiting the foregoing, you agree to not use the Services to:</p>
                    <p>A. establish or contribute to any Campaign with the implicit or express purpose relating to any of the following:</p>
                    <ol>
                        <li>any activity that violates any law or governmental regulation;</li>
                        <li>content or campaigns that are fraudulent, misleading, inaccurate, dishonest, impossible or imitating any other person or fundraising campaign (whether on the Platform or not);</li>
                        <li>illegal drugs, narcotics, steroids, controlled substances or other products that present a risk to consumer safety or any related paraphernalia;</li>
                        <li>knives, explosives, ammunition, firearms, or other weaponry or accessories;</li>
                        <li>annuities, investments, equity or lottery contracts, lay-away systems, off-shore banking or similar transactions, money service businesses (including currency exchanges, check cashing or the like), debt collection or crypto-currencies;</li>
                        <li>gambling, gaming and/or any other activity with an entry fee and a prize, including, but not limited to casino games, sports betting, fantasy sports, horse or greyhound racing, lottery tickets, other ventures that facilitate gambling, games of skill or chance (whether or not it is legally defined as a lottery) or sweepstakes;</li>
                        <li>the promotion of hate, violence, harassment, discrimination, terrorism, or intolerance of any kind relating to race, ethnicity, national origin, religious affiliation, sexual orientation, sex, gender or gender identity, or serious disabilities or diseases;</li>
                        <li>activities with, in, or involving countries, regions, governments, persons, or entities that are subject to U.K. and other economic sanctions under applicable law, unless such activities are expressly authorised by the appropriate governmental authority;</li>
                        <li>ransom, human trafficking or exploitation;</li>
                        <li>pornography or other sexual content;</li>
                        <li>offensive, graphic, perverse or sensitive content;</li>
                        <li>the defense or support of anyone alleged to be involved in criminal activity;</li>
                        <li>offering monetary rewards, including gift cards;</li>
                        <li>transactions for the sale of items before the seller has control or possession of the item;</li>
                        <li>collection of payments on behalf of merchants by payment processors or otherwise; or</li>
                        <li>credit repair or debt settlement services.</li>
                    </ol>
                    <p>B. transmit or otherwise upload any content that (i) infringes any intellectual property or other proprietary rights of any party; (ii) you do not have a right to upload under any law or under contractual or fiduciary relationships; (iii) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; (iv) poses or creates a privacy or security risk to any person; (v) constitutes unsolicited or unauthorised advertising, promotional materials, commercial activities and/or sales, “junk mail,” “spam,” “chain letters,” “pyramid schemes,” “contests,” “sweepstakes,” or any other form of solicitation; or (vi) in the sole judgment of WJCW CF, is objectionable or which restricts or inhibits any other person from using or enjoying the Services, or which may expose WJCW CF or its users to any harm or liability of any type; or</p>
                    <p>C. interfere with or disrupt the Services or servers or networks connected to the Services, or disobey any requirements, procedures, policies or regulations of networks connected to the Services; or</p>
                    <p>D. harvest or collect email addresses or other contact information of other users from the Services by electronic or other means.</p>
                    <p><strong>Gifts/Donations:</strong> In order to contribute to a “campaign” or to a charity, a “donor” will be required to provide WJCW CF information regarding its credit card or other payment instruments. You, as a Donor, confirm to WJCW CF that such information is true and that you are authorised to use the payment method. <strong>You agree that a certain minimum gift/donation amount may apply and that all gift/donation payments are final and are non-refundable.</strong> Donors may have the option to contribute recurring period gift/donations, and in electing to contribute on a recurring basis, you, as a Donor (i) agree to promptly update your account information with any changes (for example, a change in your billing address or credit card expiration date) that may occur and to pay the gift/donation amount that you specify, and (ii) hereby authorise WJCW CF to bill your payment instrument in advance on a periodic basis until you terminate such periodic payments, which can be done at any time through the user portal via the WJCW CF website. Furthermore, you as a user of this platform are solely responsible for sending and receiving gifts/donations from other parties; this responsibility does not lie with WJCW CF.</p>
                    <h2>Gifting and Donating:</h2>
                    <p>A user of WJCW CF Platform making a gift/donation is deemed a “donor” and may choose one of the following “Gift/Donations Levels” as set out in the WJCW Membership Form and as explained further on the WJCW CF website:</p>
                    <h3>Gift/Donation Levels <span style="color: #f70909;">*</span></h3>
                    
                    <?php include "gift_donations_levels_t&c.php"; ?>
                    
                    <p><span style="color: #f70909;"><b>*N.B.: these figures are approximate and may be more or less at times.</b></span></p>
                    <p>Please note it is your absolute choice to gift/donate at the level or levels you so desire. According to your gifts/donation level, a member must “give” and “receive” through all twelve stages of the software platform in order to qualify for WJCW benefits and can recycle repeatedly as many times as you like.</p>
                    <p>Please note that if you do not follow the rules or are not an active member of WJCW CF, you risk losing your membership and status as a shareholder. For members to note that all money gifted via WJCW CF is non-refundable.</p>
                    <p><strong>Fees:</strong> WJCW CF charges an annual fee for the use of the software platform and licensing. <strong>This fee is subject to change but for the year 2020/2021 is an annual sum of £12 GBP.</strong> This is separate from the 50% of each “gift/donation level” which is given to WJCW and the remaining 50% is kept by the user/member. More information on fees can be found on the WJCW website. We reserve the right to change WJCW CF’s fee pricing at any time with reasonable notice of 30 days via the online WJCW CF Platform or in an email to you, at WJCW CF’s discretion. Your continued use of WJCW CF services after the fee change becomes effective constitutes your acceptance of the updated fees. All fees referred to in these Terms of Service are exclusive of Value Added Tax, Goods and Services Tax and any other taxes, where applicable.</p>
                    <p><strong>Account Holds:</strong> From time to time, WJCW CF may place a hold on a campaign account (a “Hold”), restricting withdrawals (defined herein) by a campaign organiser. Some of the reasons that we may place a Hold on a campaign account include (i) if there is reason to believe that information provided in the account is misleading, false or fraudulent, or that funds are being used in a prohibited manner, (ii) if the funds available should be provided directly to a person other than the campaign organiser (such as a legal beneficiary or person entitled by law to act on behalf of a campaign organiser), (iii) if we have reason to believe that these Terms of Service have been violated, or (iv) if required in order to comply with a legally binding court order. If you have questions about an account hold or need information about how to resolve this, please contact WJCW CF via the contact details on the website.</p>
                    <p><strong>Withdrawing Gifts/Donations from a Campaign:</strong> You, as a campaign organiser (or, as applicable, the beneficiary designated by the campaign), may withdraw gifts/donations to your campaign at any time up to the full amount of all gifts/donations credited to your campaign, less Fees and any previously withdrawn amounts (“withdrawals”) and subject to any Holds that we or our payment partners may place on your campaign account. A campaign organiser may withdraw gifts/donations by transferring to their eWallet as provided by WJCW CF. While WJCW CF strives to make withdrawals available to you promptly, you acknowledge and agree that withdrawals may not be available to you for use immediately, and WJCW CF does not guarantee that withdrawals will be available to you within any specific time frame. WJCW CF expressly disclaims any and all responsibility for any delay or inability to access and use withdrawals at any specified time, and any consequences arising from such delay or inability. You, as a campaign organiser, are responsible for ensuring that the information you provide to WJCW CF in order to process a withdrawal, including your eWallet account information, is accurate and up to date.</p>
                    <p><strong>Third-Party Material:</strong> Under no circumstances will WJCW CF be liable in any way for any content or materials of any third parties (including users and campaign organiser), including, but not limited to, for any errors or omissions in any content, or for any loss or damage of any kind incurred as a result of the use of any such content. You acknowledge that WJCW CF does not pre-screen content, but that WJCW CF and its technicals have the right (but not the obligation) to refuse/remove any content that is available via the services. Without limiting the foregoing, WJCW CF will have the right to remove any content that violates these Terms of Service or is deemed by WJCW CF, in its sole discretion, to be otherwise objectionable.</p>
                    <p><strong>User Content Transmitted via the WJCW CF online platform:</strong> With respect to content, photos, videos, images, trademarks, logos, brands or other materials, otherwise known as user content, you upload or post on the online platform or share with other users or recipients, confirm that you own all rights or otherwise have all necessary rights and consents to (and to allow others to) fully exploit, such user content, including, without limitation, as it concerns all copyrights, trademark rights and rights of publicity or privacy-related thereto. By uploading any user content you hereby grant and will grant WJCW CF and its affiliated companies a non-exclusive, worldwide, royalty-free, fully paid up, transferable, sublicensable, perpetual, irrevocable license to copy, display, upload, perform, distribute, store, modify and otherwise use your User Content in connection with the operation of the services or the promotion, advertising or marketing thereof, in any form, medium or technology now known or later developed. Without limiting the foregoing, if any user content contains your name, image or likeness, you hereby release and hold harmless WJCW CF and its contractors and employees, from (i) all claims for invasion of privacy, publicity or libel, (ii) any liability or other claims by virtue of any blurring, distortion, alteration, optical illusion, or other use or exploitation of your name, image or likeness, and (iii) any liability for claims made by you (or any successor to any claim you might bring) in connection with your User Content, name, image or likeness. You waive any right to inspect or approve any intermediary version(s) or finished version(s) of the results of the use of your User Content (including your name, image or likeness). Further, if any person (other than you) appears in your User Content, you represent and warrant that you have secured all necessary licenses, waivers, and releases from such person(s) for the benefit of WJCW CF in a manner fully consistent with the licenses, waivers, and releases set forth above. You further acknowledge that your participation in the services and submission of User Content is voluntary and that you will not receive financial compensation of any type associated with the licenses, waivers, and releases set forth herein (or WJCW CF exploitation thereof), and that the sole consideration for the subject matter of this agreement is the opportunity to use the WJCW CF services.</p>
                    <p>You acknowledge and agree that any questions, comments, suggestions, ideas, feedback or other information about the services provided by WJCW CF (“Submissions”) provided by you are non-confidential and WJCW CF will be entitled to the unrestricted use and dissemination of these Submissions for any purpose, commercial or otherwise, without acknowledgment or compensation to you.</p>
                    <p>You acknowledge and agree that WJCW CF may preserve content and may also disclose content if required to do so by law or in the good-faith belief that such preservation or disclosure is reasonably necessary to (a) comply with legal process, applicable laws or government requests; (b) enforce these Terms of Service; (c) respond to claims that any content violates the rights of third parties; or (d) protect the rights, property, or personal safety of WJCW CF, its users or the public.</p>
                    <p><strong>Copyright and/or Intellectual Property Complaints:</strong> WJCW CF respects the intellectual property of others, and we ask our users to do the same. If you believe that your work has been duplicated in a manner that contravenes the intellectual property rights of the UK, you should notify WJCW CF by making representations to WJCW head office, the details of which can be found on the WJCW website.</p>
                    <h2>Third Party Websites/Services</h2>
                    <p>The Services may provide or facilitate, or third parties may provide, links or other access to other sites, services and resources on the Internet. WJCW CF has no control over such sites, services and resources and WJCW CF is not responsible for and does not endorse such sites, services, and resources. You further acknowledge and agree that WJCW CF will not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any content, events, goods or services available on or through any such site, service or resource. Any dealings you have with third parties found while using the Services are between you and the third party, and you agree that WJCW CF is not liable for any loss or claim that you may have against any such third party.</p>
                    <h2>Disclaimer of Warranties</h2>
                    <p>YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. WJCW CF AND ITS AFFILIATES EXPRESSLY DISCLAIM AND EXCLUDE, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, ALL WARRANTIES, CONDITIONS, AND REPRESENTATIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT.</p>
                    <p>WJCW CF AND ITS AFFILIATES MAKE NO WARRANTY OR CONDITION THAT (I) THE SERVICE WILL MEET YOUR REQUIREMENTS, (II) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (III) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, OR (IV) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS.</p>
                    <h2>Limitation of Liability</h2>
                    <p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT NEITHER WJCW CF NOR ITS AFFILIATES WILL BE LIABLE FOR ANY (A) INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, (B) DAMAGES FOR LOSS OF PROFITS, (C) DAMAGES FOR LOSS OF GOODWILL, (D) DAMAGES FOR LOSS OF USE, (E) LOSS OR CORRUPTION OF DATA, OR (F) OTHER INTANGIBLE LOSSES (EVEN IF WJCW CF HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, RESULTING FROM (I) THE USE OR THE INABILITY TO USE THE SERVICE; (II) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICE; (III) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (IV) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; OR (V) ANY OTHER MATTER RELATING TO THE SERVICE.</p>
                    <p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE LIMITATIONS SET FORTH ABOVE MAY NOT APPLY TO YOU. IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE SERVICE OR WITH THESE TERMS OF SERVICE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USE OF THE SERVICES.</p>
                    <h2>Termination</h2>
                    <p>You agree that WJCW CF, in its sole discretion, may suspend or terminate your account (or any part thereof) or use of the services and remove and discard any content within the Services under reasonable circumstances, including, without limitation, for lack of use or if WJCW CF believes that you have violated or acted inconsistently with the letter or spirit of these Terms of Service and the WJCW Objectives stated above, as well as any other reason as set out in these Terms of Service.</p>
                    <p>Any suspected fraudulent, abusive or illegal activity that may be grounds for termination of your use of Services, may be referred to appropriate law enforcement authorities. You agree that any termination of your access to the Services under any provision of these Terms of Service may be affected without prior notice, and acknowledge and agree that WJCW CF may immediately deactivate or delete your account and all related information and files in your account and/or bar any further access to such files or the services where such deactivation or deletion is permitted under these Terms of Service. Further, you agree that WJCW CF will not be liable to you or any third party for any termination of your access to the Services.</p>
                    <h2>User Disputes</h2>
                    <p>You agree that you are solely responsible for your interactions with any other user in connection with the Services within the rules set by WJCW CF. However, WJCW CF will have no liability or responsibility with respect thereto and is not responsible for any misrepresentation of our messages and rules. WJCW CF reserves the right but has no obligation to become involved in any way with disputes between you and any other user of the Services.</p>
                    <h2>General</h2>
                    <p>These Terms of Service constitute the entire agreement between you and 50WJCW CF and govern your use of the Services, superseding any prior agreements between you and WJCW CF with respect to the Services. You also may be subject to additional terms and conditions that may apply when you use affiliate or third-party services, third-party content or third-party software. These Terms of Service will be governed by the laws of the UK without regard to its conflict of law provisions. With respect to any disputes or claims not subject to arbitration, as set forth above, you and WJCW CF agree to submit to the legal jurisdiction of the country/nation in which WJCW CF was registered as a company. The failure of WJCW CF to exercise or enforce any right or provision of these Terms of Service will not constitute a waiver of such right or provision. If any provision of these Terms of Service is found by a court of competent jurisdiction to be (or are otherwise) invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in the provision, and the other provisions of these Terms of Service remain in full force and effect. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Services or these Terms of Service must be filed within one (1) year after such claim or cause of action arose or be forever barred. A printed version of this agreement and of any notice given in electronic form will be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. You may not assign these Terms of Service without the prior written consent of WJCW CF, but WJCW CF may assign or transfer these Terms of Service, in whole or in part, without restriction. If we fail to enforce any of our rights, that does not result in a waiver of that right. The section titles in these Terms of Service are for convenience only and have no legal or contractual effect. The services may provide notices to you of changes to these Terms of Service or other matters by displaying notices or links to notices generally on the WJCW CF platform.</p>
                </div>
            </div>
        </section>
        <!-- CARDS END -->

        <!-- Video Section -->


    </main>
    <!-- Footer -->
    <?php include("../header_footer/footer.php") ?>
    <!-- Footer Ends -->
</body>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="assets/links/owl.carousel.min.js"></script>
<script src="js/site.js"></script>

</html>